/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.adriianh

import com.github.adriianh.command.*
import com.github.adriianh.common.TaskManager
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.main
import com.github.ajalt.clikt.core.subcommands

class ToDo : CliktCommand() {
    private val manager = TaskManager()

    override fun run() = Unit

    init {
        subcommands(
            FileCommand(manager),
            CreateCommand(manager),
            DeleteCommand(manager),
            EditCommand(manager),
            CompleteCommand(manager),
            ListCommand(manager)
        )
    }
}

fun main(args: Array<String>) = ToDo().main(args)